linters:
  disable:
    - godot
    - testpackage
    - nakedret
    - funlen
    - noctx
    - gofumpt
    - gocritic
    - nestif
    - dogsled
    - golint
    - stylecheck
    - gomnd
    - gocognit
    - dupl
    - deadcode
    - scopelint
    - maligned

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - gochecknoinits
        - gochecknoglobals
        - staticcheck